### ISSUE TITLE
make ServerChannel as a Pubisher[Channel]

### ISSUE THREAD

**Issue by hepin1989** [typesafehub/netty-reactive-streams#1]
I was wandering how about make the``` ServerChannel ```as ```Publisher[Channel]```,and then we setup the ChannelPipeline ,register it to eventloop.and then we may get can get the Publisher for the specified channel via``` def StreamedChannelHandler.publisher:Future[Publisher]```?
the publisher will only return and always return the same instance after the channel is active and the handler is added to the pipeline.

**Comment by hepin1989** [comment]
eg : we could turn it to StreamdTcp like
https://github.com/akka/akka/blob/release-2.3-dev/akka-stream/src/main/scala/akka/stream/scaladsl/Tcp.scala#L42

**Comment by jroper** [comment]
I think creating a publisher of channels is as simple as doing this:

```java
Bootstrap bootstrap = new Bootstrap();
PublisherHandler<Channel> publisher = new PublisherHandler<>(Channel.class);
bootstrap.handler(publisher);
bootstrap.localAddress(...);
bootstrap.group(...);
bootstrap.bind();
```

Each subscriber will then need to add handlers to the pipeline, and then they need to register the channel to an event loop.

**Comment by hepin1989** [comment]
you can't use bootstrap here,cause it will register the channel to the eventloop for you .
here we should control it via manually.

**Comment by jroper** [comment]
It will register the `ServerSocketChannel` with an event loop, but that's ok, we want that.  The `SocketChannel` for each incoming connection though won't be registered, that will be up to the subscriber.  The thing that usually does that is the `ServerBootstrap`, but we're not using a `ServerBootstrap`, we're using an ordinary `Bootstrap`.

Anyway, I just wrote a test to test this, it works, the actual code for setup is here:

https://github.com/typesafehub/netty-reactive-streams/blob/master/netty-reactive-streams/src/test/java/com/typesafe/netty/ChannelPublisherTest.java#L37
